# Generated by Django 3.0.2 on 2020-06-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='from_api',
            field=models.BooleanField(default=False),
        ),
    ]
