# Generated by Django 3.0.2 on 2020-06-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200608_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commission',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
