# Generated by Django 3.0.2 on 2020-06-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='commission',
        ),
        migrations.AddField(
            model_name='profile',
            name='commission',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
