# Generated by Django 4.2.6 on 2023-10-28 16:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import hitcount.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_Price', models.PositiveIntegerField(default=0)),
                ('meal_Plans', models.TextField()),
                ('duration', models.PositiveIntegerField(default=1)),
                ('start_Date', models.DateField()),
                ('end_Date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hotel Package',
                'verbose_name_plural': 'Hotel Packages',
                'ordering': ['package_Price', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_photo', models.ImageField(default='default.jpg', upload_to='hotel_photos')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('vat', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('star_rating', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('featured_from', models.DateField(blank=True, null=True)),
                ('featured_to', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=12, null=True)),
                ('checkin', models.TimeField(blank=True, null=True)),
                ('checkout', models.TimeField(blank=True, null=True)),
                ('policies', models.TextField(blank=True, null=True)),
                ('has_conference', models.BooleanField(default=False)),
                ('is_apartment', models.BooleanField(default=False)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('airport_transport', models.BooleanField(default=False)),
                ('night_club', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('restaurant', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('laundry_services', models.BooleanField(default=False)),
                ('bar_lounge', models.BooleanField(default=False)),
                ('disabled_services', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
                ('shuttle_bus_service', models.BooleanField(default=False)),
                ('cards_accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Hotels',
                'ordering': ('-created_at',),
            },
            bases=(models.Model, hitcount.models.HitCountMixin),
        ),
        migrations.CreateModel(
            name='HotelTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Hotel Types',
            },
        ),
        migrations.CreateModel(
            name='Itinirery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Package Itinireries',
            },
        ),
        migrations.CreateModel(
            name='PackagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='package_photos')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='PackageTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Package Types',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='hotel_photos')),
            ],
            options={
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_photo', models.ImageField(default='default.jpg', upload_to='room_photos')),
                ('room_Name', models.CharField(max_length=200)),
                ('room_details', models.CharField(max_length=500)),
                ('max_adults', models.PositiveIntegerField(default=1)),
                ('max_child', models.PositiveIntegerField(default=1)),
                ('extra_beds', models.PositiveIntegerField(default=0)),
                ('extra_bed_price', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('room_Price', models.PositiveIntegerField(default=1)),
                ('total_Rooms', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('is_conference_room', models.BooleanField(default=False)),
                ('is_apartment', models.BooleanField(default=False)),
                ('free_toiletries', models.BooleanField(default=False)),
                ('water_body_view', models.BooleanField(default=False)),
                ('safe_deposit_box', models.BooleanField(default=False)),
                ('lcd_tv', models.BooleanField(default=False)),
                ('pay_tv', models.BooleanField(default=False)),
                ('mini_bar', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('blackout_drapes', models.BooleanField(default=False)),
                ('telephone', models.BooleanField(default=False)),
                ('ironing_facilities', models.BooleanField(default=False)),
                ('desk', models.BooleanField(default=False)),
                ('hair_dryer', models.BooleanField(default=False)),
                ('extra_towels', models.BooleanField(default=False)),
                ('bathrobes', models.BooleanField(default=False)),
                ('wake_up_service', models.BooleanField(default=False)),
                ('electric_kettle', models.BooleanField(default=False)),
                ('warddrobe', models.BooleanField(default=False)),
                ('toilet_paper', models.BooleanField(default=False)),
                ('slippers', models.BooleanField(default=False)),
                ('toilet', models.BooleanField(default=False)),
                ('alarm_clock', models.BooleanField(default=False)),
                ('tea_coffee_maker', models.BooleanField(default=False)),
                ('bathtub_shower', models.BooleanField(default=False)),
                ('makeup_shaving_mirror', models.BooleanField(default=False)),
                ('city_view', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('cribs_infant_beds', models.BooleanField(default=False)),
                ('daily_housekeeping', models.BooleanField(default=False)),
                ('garden_view', models.BooleanField(default=False)),
                ('projector', models.BooleanField(default=False)),
                ('screen', models.BooleanField(default=False)),
                ('conference_phone', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
                ('free_wifi', models.BooleanField(default=False)),
                ('speakers', models.BooleanField(default=False)),
                ('whiteboard', models.BooleanField(default=False)),
                ('sockets', models.BooleanField(default=False)),
                ('coffee', models.BooleanField(default=False)),
                ('monitors', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotels')),
            ],
            options={
                'verbose_name_plural': 'Rooms',
                'ordering': ['room_Price', 'updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Room Types',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='slider_photos')),
                ('header_text', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.CharField(blank=True, max_length=120, null=True)),
                ('active', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_Date', models.DateField(blank=True, null=True)),
                ('end_Date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Sliders',
                'ordering': ['-start_Date', '-end_Date'],
            },
        ),
        migrations.CreateModel(
            name='RoomPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(upload_to='room_photos')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.room')),
            ],
            options={
                'verbose_name_plural': 'Room Photos',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.roomtypes'),
        ),
    ]
