# Generated by Django 3.0.2 on 2020-06-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='has_conference',
            field=models.BooleanField(default=False),
        ),
    ]
