# Generated by Django 3.0.2 on 2020-01-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20200123_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='main_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.Hotels'),
        ),
    ]
