# Generated by Django 3.0.2 on 2020-03-03 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_slider'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['-start_Date', '-end_Date'], 'verbose_name_plural': 'Sliders'},
        ),
    ]
