# Generated by Django 3.0.2 on 2020-06-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_room_has_conference'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='has_conference',
            new_name='is_conference_room',
        ),
    ]
