# Generated by Django 3.0.2 on 2020-01-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200124_0710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name_plural': 'Photos'},
        ),
        migrations.AddField(
            model_name='hotels',
            name='property_photo',
            field=models.ImageField(default='default.jpg', upload_to='hotel_photos'),
        ),
    ]
