# Generated by Django 3.0.2 on 2020-06-23 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200622_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelpackages',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels'),
        ),
    ]
