# Generated by Django 3.0.2 on 2020-03-09 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0003_auto_20200303_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_photo', models.ImageField(default='default.jpg', upload_to='confrenceroom_photos')),
                ('room_Name', models.CharField(max_length=200)),
                ('room_details', models.TextField(blank=True, null=True)),
                ('room_Capacity', models.PositiveIntegerField(default=10)),
                ('slug', models.SlugField(unique=True)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Conference Rooms',
                'unique_together': {('room_Name', 'slug')},
            },
        ),
    ]
