# Generated by Django 3.0.2 on 2020-06-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20200623_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_apartment',
            field=models.BooleanField(default=False),
        ),
    ]
