# Generated by Django 3.0.2 on 2020-06-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_room_is_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='is_apartment',
            field=models.BooleanField(default=False),
        ),
    ]
