# Generated by Django 3.0.2 on 2020-03-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20200309_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='room_Price',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
