# Generated by Django 3.0.2 on 2020-01-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20200127_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
