# Generated by Django 3.0.2 on 2020-01-28 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_auto_20200128_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hotels',
            unique_together={('name', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('room_Name', 'slug')},
        ),
    ]
