# Generated by Django 3.0.2 on 2020-03-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_cartconferenceitems_hotel_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartconferenceitems',
            name='RoomCheckOut',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartconferenceitems',
            name='nights',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
