# Generated by Django 3.0.2 on 2020-03-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20200311_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartconferenceitems',
            name='double_room_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='cartconferenceitems',
            name='double_room_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='cartconferenceitems',
            name='single_room_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
        migrations.AddField(
            model_name='cartconferenceitems',
            name='single_room_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
