# Generated by Django 3.0.2 on 2020-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_auto_20200311_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='room_discount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=1000),
        ),
    ]
