# Generated by Django 3.0.2 on 2020-03-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_conferenceroom_room_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconferenceitems',
            name='double_room_total',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartconferenceitems',
            name='single_room_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
