# Generated by Django 3.0.2 on 2020-01-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_auto_20200129_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='CheckIn',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='CheckOut',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='active',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guestFirstName',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='guestLastName',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
    ]
