# Generated by Django 3.0.2 on 2020-03-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_auto_20200311_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartconferenceitems',
            name='double_room_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartconferenceitems',
            name='single_room_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
