# Generated by Django 3.0.2 on 2020-01-30 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20200129_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='CheckIn',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='CheckOut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rooms',
        ),
        migrations.AddField(
            model_name='reservation',
            name='rooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels.Room'),
        ),
    ]
