# Generated by Django 3.0.2 on 2020-03-17 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_auto_20200311_1649'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_Price', 'created_at'], 'verbose_name_plural': 'Rooms'},
        ),
    ]
