# Generated by Django 3.0.2 on 2020-03-17 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_auto_20200317_0619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conferenceroom',
            options={'ordering': ('room_Price', 'created_at'), 'verbose_name_plural': 'Conference Rooms'},
        ),
        migrations.AlterModelOptions(
            name='hotelpackages',
            options={'ordering': ('package_Price', 'created_at'), 'verbose_name': 'Hotel Package', 'verbose_name_plural': 'Hotel Packages'},
        ),
    ]
