# Generated by Django 3.0.2 on 2020-03-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_auto_20200317_0831'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotelpackages',
            options={'ordering': ['package_Price', 'created_at'], 'verbose_name': 'Hotel Package', 'verbose_name_plural': 'Hotel Packages'},
        ),
    ]
