# Generated by Django 3.0.2 on 2020-01-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_reservation_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='rooms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
