# Generated by Django 3.0.2 on 2020-03-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0018_auto_20200317_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotels',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Hotels'},
        ),
        migrations.AddField(
            model_name='hotels',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
