# Generated by Django 3.0.2 on 2020-03-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_auto_20200320_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='conferenceroom',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='packages',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='packages',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
