# Generated by Django 3.0.2 on 2020-03-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0020_auto_20200320_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferenceroom',
            name='conference',
        ),
        migrations.RemoveField(
            model_name='conferenceroom',
            name='featured',
        ),
        migrations.AddField(
            model_name='hotels',
            name='has_conference',
            field=models.BooleanField(default=False),
        ),
    ]
