# Generated by Django 3.0.2 on 2020-01-31 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_auto_20200131_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='CheckIn',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitems',
            name='CheckOut',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
