# Generated by Django 3.0.2 on 2020-02-01 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0022_auto_20200131_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='CheckIn',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='CheckOut',
            field=models.DateField(blank=True, null=True),
        ),
    ]
