# Generated by Django 3.0.2 on 2020-02-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0023_auto_20200201_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='stay_duration',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
