# Generated by Django 3.0.2 on 2020-02-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0025_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('service_photo', models.ImageField(default='default.jpg', upload_to='service_photos')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Room')),
            ],
            options={
                'verbose_name_plural': 'Services',
            },
        ),
    ]
