# Generated by Django 3.0.2 on 2020-02-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_hotelservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotelservice',
            old_name='room',
            new_name='hotel',
        ),
    ]
