# Generated by Django 3.0.2 on 2020-02-03 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0027_auto_20200203_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelservice',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotels'),
        ),
    ]
