# Generated by Django 3.0.2 on 2020-02-05 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0028_auto_20200203_0950'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
