# Generated by Django 3.0.2 on 2020-02-27 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=120)),
                ('payment_option', models.CharField(choices=[('pay_on_checkin', 'Pay on CheckIn'), ('visa_mastercard', 'Visa or MasterCard')], default='pay_on_checkin', max_length=120)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
        migrations.CreateModel(
            name='PackageReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('status', models.CharField(choices=[('Started', 'Started'), ('Abandoned', 'Abandoned'), ('Finished', 'Finished')], default='Started', max_length=120)),
                ('payment_option', models.CharField(choices=[('pay_on_checkin', 'Pay on CheckIn'), ('visa_mastercard', 'Visa or MasterCard')], default='pay_on_checkin', max_length=120)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Cart')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Package Reservations',
            },
        ),
    ]
