# Generated by Django 3.0.2 on 2020-03-03 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200303_1749'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.')], default='mr', max_length=120)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile_Number', models.CharField(max_length=12)),
                ('reservation_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('payment_option', models.CharField(choices=[('pay_on_checkin', 'Pay on CheckIn'), ('visa_mastercard', 'Visa or MasterCard')], default='pay_on_checkin', max_length=120)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Cart')),
            ],
            options={
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
