# Generated by Django 3.0.2 on 2020-06-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
        ('reservations', '0002_booking_total_guests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='checkout',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='final_total',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='name_of_guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='organisation_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='register_as_user',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_qty',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='tax_total',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='total_guests',
        ),
        migrations.AlterField(
            model_name='booking',
            name='mobile_Number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.CreateModel(
            name='BookingItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_qty', models.PositiveIntegerField(default=1)),
                ('total_guests', models.PositiveIntegerField(default=1)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('tax_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('checkin', models.DateField(blank=True, null=True)),
                ('checkout', models.DateField(blank=True, null=True)),
                ('stay_duration', models.PositiveIntegerField(default=1)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Room')),
            ],
            options={
                'verbose_name_plural': 'Booking items',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(to='reservations.BookingItems'),
        ),
    ]
