# Generated by Django 3.0.2 on 2020-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
