# Generated by Django 3.0.2 on 2020-02-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200207_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_option',
            field=models.CharField(choices=[('pay_on_checkin', 'Pay on CheckIn'), ('visa_mastercard', 'Visa or MasterCard')], default='pay_on_checkin', max_length=120),
        ),
    ]
