# Generated by Django 3.0.2 on 2020-03-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_booking_final_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='register',
            field=models.BooleanField(default=False),
        ),
    ]
