# Generated by Django 3.0.2 on 2020-06-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20200614_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(related_name='BookingItems', to='reservations.BookingItems'),
        ),
    ]
