# Generated by Django 3.0.2 on 2020-02-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
