# Generated by Django 3.0.2 on 2020-06-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200617_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
