# Generated by Django 3.0.2 on 2020-06-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_booking_guest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitems',
            old_name='final_total',
            new_name='sub_total',
        ),
        migrations.AddField(
            model_name='booking',
            name='final_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
