# Generated by Django 3.0.2 on 2020-03-10 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_cartconferenceitems_hotel_room'),
        ('reservations', '0005_auto_20200306_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('mobile_Number', models.CharField(max_length=12)),
                ('reservation_id', models.CharField(default='ABC', max_length=120, unique=True)),
                ('number_of_guests', models.PositiveIntegerField(default=10)),
                ('start_time', models.TimeField()),
                ('attachment', models.FileField(upload_to='pay_attachments')),
                ('number_of_nights', models.PositiveIntegerField(default=1)),
                ('final_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=1000)),
                ('name_of_guests', models.TextField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Cart')),
                ('rooms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.ConferenceRoom')),
            ],
            options={
                'verbose_name_plural': 'Conference Reservations',
            },
        ),
    ]
