# Generated by Django 3.0.2 on 2020-03-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_auto_20200311_1238'),
        ('reservations', '0006_conferencereservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conferencereservation',
            old_name='rooms',
            new_name='crooms',
        ),
        migrations.RemoveField(
            model_name='conferencereservation',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='conferencereservation',
            name='number_of_nights',
        ),
        migrations.AddField(
            model_name='conferencereservation',
            name='hrooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.Room'),
        ),
    ]
