# Generated by Django 3.0.2 on 2020-06-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20200618_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
