# Generated by Django 3.0.2 on 2020-06-20 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_booking_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingitems',
            name='tax_total',
        ),
        migrations.AddField(
            model_name='booking',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
