# Generated by Django 3.0.2 on 2020-06-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_auto_20200622_1231'),
        ('reservations', '0009_auto_20200620_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingitems',
            old_name='room_qty',
            new_name='qty',
        ),
        migrations.AddField(
            model_name='bookingitems',
            name='hotel_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.HotelPackages'),
        ),
        migrations.AddField(
            model_name='bookingitems',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
