# Generated by Django 3.0.2 on 2020-03-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_remove_conferencereservation_room_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencereservation',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='pay_attachments'),
        ),
    ]
