# Generated by Django 3.0.2 on 2020-06-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0010_auto_20200623_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='commission_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
