# Generated by Django 3.0.2 on 2020-06-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20200630_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookingsettings',
            old_name='commission_total',
            new_name='commission',
        ),
        migrations.AddField(
            model_name='booking',
            name='commission_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=1000),
        ),
    ]
