# Generated by Django 3.0.2 on 2020-08-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0013_auto_20200630_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='items',
            field=models.ManyToManyField(to='reservations.BookingItems'),
        ),
    ]
