# Generated by Django 3.0.2 on 2020-08-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20200822_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
