# Generated by Django 3.0.2 on 2020-09-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0015_booking_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packagereservation',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='packagereservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConferenceReservation',
        ),
        migrations.DeleteModel(
            name='PackageReservation',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
