# Generated by Django 3.1.3 on 2020-12-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_auto_20200907_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Bookings'},
        ),
    ]
